module.exports.config = {
  name: "girlpic",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "BLACK",
  description: "Random 6-pack photos",
  commandCategory: "Random-IMG",
  usages: "dpg",
  cooldowns: 2,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
    var link = [
"https://i.imgur.com/gx96pt9.jpeg",
"https://i.imgur.com/Yq2dNvD.jpeg",
"https://i.imgur.com/204H9no.jpeg",
"https://i.imgur.com/bmKahkk.jpeg",
"https://i.imgur.com/d9Z4e5N.jpeg",
"https://i.imgur.com/Vtu7pVo.jpeg",
"https://i.imgur.com/p5Jvjjj.jpeg",
"https://i.imgur.com/7e8xUI2.jpeg",
"https://i.imgur.com/ejPSHRi.jpeg",
"https://i.imgur.com/ompIx4W.jpeg",
"https://i.imgur.com/VFoNkte.jpeg",
"https://i.imgur.com/uwszp6r.jpeg",
"https://i.imgur.com/qZWig6p.jpeg",
"https://i.imgur.com/Dw1D2Ji.jpeg",
"https://i.imgur.com/fYJrOY5.jpeg",
"https://i.imgur.com/o5myzQ8.jpeg",
"https://i.imgur.com/DGk60tJ.jpeg",
"https://i.imgur.com/vmawGZc.jpeg",
"https://i.imgur.com/r9Bo2Qn.jpeg",
"https://i.imgur.com/iOBx0Qg.jpeg",
"https://i.imgur.com/xV58bdv.jpeg",
"https://i.imgur.com/fHUlyEB.jpeg",
"https://i.imgur.com/Yd4aQo4.jpeg",
"https://i.imgur.com/6HB72QA.jpeg",
"https://i.imgur.com/i3C2XCz.jpeg",
"https://i.imgur.com/8UIu17f.jpeg",
"https://i.imgur.com/baIlvEg.jpeg",
"https://i.imgur.com/HYLjwxj.jpeg",
"https://i.imgur.com/4PtQ24J.jpeg",
"https://i.imgur.com/yCIGTs8.jpeg",
"https://i.imgur.com/nEQDVij.jpeg",
"https://i.imgur.com/IuQydQC.jpeg",
"https://i.imgur.com/2YbMuHD.jpeg",
"https://i.imgur.com/HrJUijs.jpeg",
"https://i.imgur.com/EWXZJ8j.jpeg",
"https://i.imgur.com/Cxbv5Qv.jpeg",
"https://i.imgur.com/mdZl6YA.jpeg",
"https://i.imgur.com/KgS2dXP.jpeg",
"https://i.imgur.com/fSK8GbF.jpeg",
"https://i.imgur.com/rKHoovj.jpeg",
"https://i.imgur.com/DDN2FqE.jpeg",
"https://i.imgur.com/8SnuMmH.jpeg",
"https://i.imgur.com/9rI7WM9.jpeg",
"https://i.imgur.com/GY3obl2.jpeg",
"https://i.imgur.com/R5aamUt.jpeg",
"https://i.imgur.com/EsTcNLF.jpeg",
"https://i.imgur.com/srUx9TF.jpeg",
"https://i.imgur.com/6VgsDuW.jpeg",
"https://i.imgur.com/8grFh7K.jpeg",
"https://i.imgur.com/L529nyo.jpeg",
"https://i.imgur.com/4wGgw4c.jpeg",
"https://i.imgur.com/ZJ2ogWB.jpeg",
"https://i.imgur.com/8x1xp5m.jpeg",
"https://i.imgur.com/gvlx61F.jpeg",
"https://i.imgur.com/3GQpmdm.jpeg",
"https://i.imgur.com/n7094fM.jpeg",
"https://i.imgur.com/NCRxft1.jpeg",
"https://i.imgur.com/APKeEDx.jpeg",
"https://i.imgur.com/4p5IUJ8.jpeg",
"https://i.imgur.com/8XqAylA.jpeg",
"https://i.imgur.com/jcHHovk.jpeg",
"https://i.imgur.com/cCspFwy.jpeg",
"https://i.imgur.com/MmXGShA.jpeg",
"https://i.imgur.com/k7ASVnP.jpeg",
"https://i.imgur.com/ONZ12Oi.jpeg",
"https://i.imgur.com/06gKphw.jpeg",
"https://i.imgur.com/EDef2sL.jpeg",
"https://i.imgur.com/pxmjXyu.jpeg",
"https://i.imgur.com/adG13Pm.jpeg",
"https://i.imgur.com/Mg1LfrK.jpeg",
"https://i.imgur.com/V6IdXAQ.jpeg",
"https://i.imgur.com/MrKzxdp.jpeg",
"",
"",
"",
"",
"",
"",
"",
"",
"https://i.imgur.com/aV4WVsq.jpg"
     ];
     var callback = () => api.sendMessage({body:`𝐌𝐀𝐃𝐄 𝐁𝐘𝐄 𝐌𝐑.. 𝐂𝐇𝐔𝐙𝐀 ❢`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"));  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
   };